#!/usr/bin/env sh

[ "$#" -eq 0 ] && exit 1

template="set timeout = 0
set default = 0

font=\"/boot/grub/fonts/unicode.pf2\"

menuentry \"potatOS\" {
    multiboot /boot/%s
    module /boot/initramfs initramfs
    module /boot/spud-%s.map spud-%s.map
    boot
}
"

printf "$template" "$1" "$2" "$2" > fsroot/boot/grub/grub.cfg
