#!/usr/bin/env sh

usage() {
    printf "usage: $0 [debug] [usage]\n" 2>&1
    exit 1
}

main() {
    GDB="toolchain/i686-tools/bin/i686-elf-gdb"
    QEMU="qemu-system-x86_64"

    [ "$#" -eq 0 ] && {
        $QEMU -m 512M \
		-no-reboot \
		-serial stdio \
		-no-shutdown \
		-hda potatOS.iso
        return
    }

    case "$1" in
    "debug")
        $QEMU -m 256M -S -s -no-reboot -no-shutdown -hda potatOS.iso &
        $GDB -x .gdbinit;;
    "usage")
        usage;;
    esac
}

main "$@"
